#!/usr/bin/env -S deno run -A --no-check --ext ts
import * as path from 'https://deno.land/std/path/mod.ts'
import { loadSync } from 'https://deno.land/std/dotenv/mod.ts'
import { Agent } from './Agent.ts'

loadSync({
  export: true,
  allowEmptyValues: true,
  envPath: path.join(path.dirname(path.fromFileUrl(import.meta.url)), '.env'),
})

const zsh = (input: string) =>
  Agent.createAzure()
    .user(
      `
You are acting as a translator that translates a command, specified in natural language, and turns it into a corresponding zsh command on a macos.
Respond only with code, without any explanations or comments, and without any quotes around.

I need the command for:

${input}
`,
    )
    .complete()
    .then(r => r.messages.at(-1)?.content)

const input = Deno.args.join(' ').trim()

if (input.length === 0) console.log('Empty input')
else zsh(input).then(r => console.log(r))
