#!/bin/sh
ROOT="${HOME}/.betafcc/node"

"${HOME}/.fnm/node-versions/v12.3.1/installation/bin/node" \
    "${ROOT}/node_modules/.bin/babel-node" \
    --config-file "${ROOT}/babel.config.js" \
    "${@}"
