# shellcheck disable=SC1090
source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )/prelude.sh"


::import './lib/dev_utils.sh' as ::dev_utils
# TODO: actually factor out a decent emacs wrapper
::import './lib/emacs.sh'     as ::emacs     exposing \
         emacs \
         xemacs \
         emax \
         xemax \
         rgx
::import './lib/loggers.sh'   as ::loggers
::import './lib/misc.sh'      as ::misc      exposing \
         grepless \
         rgless
::import './lib/os_utils.sh'  as ::os_utils  exposing ..
::import './lib/slicing.sh'   as ::slicing   exposing \
         take \
         drop \
         every


if ::process::is_interactive; then
    ::import "./modes.sh" as ::modes exposing ..

    +prompt powerline


    # until we fix `poetry shell`
    alias poetry_shell='. "$(dirname $(poetry run which python))/activate"'


    # default dir lister
    _exa() { exa --color=always --icons "$@" | less -XR; }
    alias l='_exa'

    # TODO: maybe check if running in kitty?
    alias icat="kitty +kitten icat"


    export EDITOR="::emacs emax_or_emacs"
fi
