# shellcheck disable=SC1090
# https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
# Note: this variable is avaiable in shell session that sourced it
# don't know how to prevent it (`local` kw is function-only)
# so I use this varname instead of a simple 'DIR'
__BASHRC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

source "${__BASHRC_DIR}/lib/os_utils.sh"
alias cd=@cd
alias mkcd=@mkcd
alias touchp=@touchp

source "${__BASHRC_DIR}/lib/slicing.sh"
alias take=@take
alias drop=@drop
alias every=@every

source "${__BASHRC_DIR}/lib/dev_utils.sh"

source "${__BASHRC_DIR}/lib/loggers.sh"

source "${__BASHRC_DIR}/lib/misc.sh"
alias grepless=@grepless
alias rgless=@rgless


# -nw for emacs means 'no-window'
alias emacs='TERM=xterm-256color XLIB_SKIP_ARGB_VISUALS=1 emacs -nw'
alias emax='XLIB_SKIP_ARGB_VISUALS=1 emacsclient -a=""'

# until we fix `poetry shell`
alias poetry_shell='. "$(dirname $(poetry run which python))/activate"'


# For sublime, -n is 'new window', -w is 'wait until closed'
export EDITOR='subl -nw'
